### PR TITLE
CSM - ATFs

### PR DESCRIPTION
**Pull request by SxMShaDoW**
Need guidance on:
- [x] Add documentation on how to run these tests and what plugins are needed to be installed (Customer Service with Service Management, Customer Service)

- [x] Modify UI tests to increase timeout to at least 30 seconds (let me know which one's fail for you).

Pre-reqs:

New York instance
Customer Service plugin installed
Customer Service with Service Management installed (com.sn_cs_sm)

Completed List:
- [x] Moved incomplete ATFs (CSP related ones) to a new issue: #186 

- [x] Update Set for CSM ATF

- [x] Create 2 dynamic test suites and place them under Customer Service Management. 1 for CSM API. 1 for CSM UI.

- [x] CSM -Update Support Profile

- [x] CSM- Accept Proposed Solution On Case

- [x] CSM- Provide Feedback on Survey

- [x] CSM- Provide requested info on case

- [x] CSM: Search On Homepage

- [x] CSM: Assign Asset on Case

- [x] CSM: Assign Case to an Agent

- [x] CSM: Assign Entitlement

- [x] CSM: Close a Case

- [x] CSM: Create CHG from Case

- [x] CSM: Create Incident from Case

- [x] CSM: Create Problem from Case

- [x] CSM: Create Product Case

- [x] CSM: Create Product Case as Customer from CSM Portal

- [x] CSM: Create Product Case as Partner from CSM Portal

- [x] CSM: Create Special Handling Notes

- [x] CSM: Escalate a Case

- [x] CSM: Escalate an Account

- [x] CSM: Time Recording

CSP Extra (don't use CSP often, so not the best person to write this test): 

- [x] CSP -Update Support Profile (my solution seemed hacky, so I won't go and create anymore of these until we discuss a better solution)

### CODE REVIEW

**Comment by SxMShaDoW** [comment]
CSM -Update Support Profile 
Update Support Profile

@jacebenson - Just wanted to ask for confirmation that you are okay with this test.
Note: I do the `sys_user` in order to make it a "true" Contact. You may want to modify your "create user" functionality to allow for "Class" to be added.

**Comment by jacebenson** [comment]
Let me load it up.

**Comment by jacebenson** [comment]
So I turned on my NY instance.
Pulled in your ATF fork
Turned on Customer Service Plugin

I couldnt find the test in the suite.  No biggie, Found it in the tests by package.
Ran it.
Got some errors;
image

The error specifical is about not seeing "Warren" on teh page.  But I see it.  Maybe the script didnt take long enough to look.  Looks like it was step 8.  I upped the time from 10, to 60 seconds.

Ran it again, Success at step 8.  Failing at step 16

Upp'd that timeout to 60 seconds.  Success.

Can you do the following.
1.  Add your test to the "Customer Service Management" one
image
2.  Up the timeouts on step's in position 8, and 16 (assert text === warren && assert number === number given) from 10 to 60. Re commit your changes, make a pull request and i'll accept.

**Comment by SxMShaDoW** [comment]
@jacebenson - I just wanted to make sure you were okay with the format / style I was doing. I will complete the other tests before opening up the PR. Thanks for doing a quick test. I guess browser / internet connection can come into play with those timeouts as it worked locally. I will make sure assert timeouts have longer timeouts.

I will add it to the CSM test suite (and create an API test suite and UI test suite)

**Comment by SxMShaDoW** [comment]
@jacebenson - So ran into a situation where I need a decision from you.

In the CSM - Create Incident from Case, the OOB tests journal entry (ie work notes) functionality. In order to test that functionality we need a sys_id as a string (because Element ID is a string not a reference). Unfortunately, none of the OOB step configurations (ie Log Message, Record Query, Server side script) output a value/sys_id as a string. 

So we need to do the following (unless you have alternatives):

Option 1 (easiest route):
* Add an output variable to server side script test step that will output a string. 
* * Downside: Upgrades may be skipped on that step

Option 2:
* Create a copy of record query step configuration and create an output variable that will output a string (we can make it generic or make it output sys_id)
* * Downside: I would probably wait on you to do this and I would work on other tests

**Comment by jacebenson** [comment]
I'd just go the easiest route.  We can log a bug and have someone else fix it later.

**Comment by SxMShaDoW** [comment]
4 completed. 15 to go.

**Comment by SxMShaDoW** [comment]
@jacebenson - could you run the suite when you get a chance. I want to make sure my output variable on server side script installs with the application. If not, I will have to go the second route.

**Comment by jacebenson** [comment]
I am still up.  Repulling it in.

**Comment by jacebenson** [comment]
So I am getting three errors, maybe I am missing a plugin to test properly;
I'll give you admin to my instance, you'll need to change the pw, but the login/pass to the instance in the video is youre username , sxmshadow 

https://www.youtube.com/watch?v=dg4UbfEol8U&feature=youtu.be

**Comment by SxMShaDoW** [comment]
@jacebenson - the reason you get those errors are because you don't have Service Management plugin installed.

https://docs.servicenow.com/bundle/newyork-customer-service-management/page/product/customer-service-management/concept/csm-integration-service-management.html

Customer Service with Service Management plugin (com.sn_cs_sm) for integration with the Incident, Problem, and Change Management applications.

**Comment by SxMShaDoW** [comment]
I haven't looked through the other OOB, but you may also want to install the Case Action status:

https://docs.servicenow.com/bundle/newyork-customer-service-management/page/product/customer-service-management/concept/customer-service-case-action-status.html

Users with the admin role can activate the Case Action Status plugin (com.snc.csm_action_status). This plugin provides a Customer Service-specific application of the Action Status Automation plugin (com.sn_action_status), which tracks blocking tasks created for customer service cases and updates the action status indicators.

**Comment by dorian-coygo** [comment]
@jacebenson - its been a crazy month or so. Next week I will hop back on this and finish it up. Sorry for the delay.

**Comment by SxMShaDoW** [comment]
I will hop back on this next week (been a crazy month or so). @jacebenson sorry for the delay.

**Comment by SxMShaDoW** [comment]
@jacebenson - I think I need you to run a test for me if you get a chance this week.

Required Pre-reqs:
* New York instance
* Customer Service plugin installed
* Customer Service with Service Management installed (com.sn_cs_sm)
* Pull my repo into it.

The biggest thing I am trying to figure out is solving the below issue:

1. I added an atf output variable (atf_output_variable) to "Run a server side script" (global/read-only step configuration) in the ATF scope. I am hoping that will transfer when someone installs this application. If not, I need a recommendation on the best way to add that output variable (or create an custom step configuration. I tried this myself, but struggled with getting the "steps" part of it).

All the "Run a server side script" does is convert a previous step record_id to a string (so it can be used by journal entry and open a service portal page):
```
	var gr = steps("dc2e76df37f50010bec7dc1873990e74").record_id;
	var sys_id_string = gr.sys_id.toString();
	outputs.u_output_string = sys_id_string;
	stepResult.setOutputMessage(gs.getMessage("Successfully outputed the sys id to '{0}'", [sys_id_string]));
	return true;
```
You can see this in action on `CSM - Portal - UI - Provide requested info on case` or `CSM - Service Management - UI - Create Incident from Case` tests

I should be done with the rest of the CSM ones either today or tomorrow. I haven't decided if I am going to do the CSP ones yet.

**Comment by SxMShaDoW** [comment]
Merry Christmas @jacebenson . We should have OOB tests for most of CSM with this PR. Just need a few test runs from you and should be good to go! I added comments in the description of this PR about what I didn't do.

**Comment by SxMShaDoW** [comment]
Moving the creation of these tests these to a new issue:
- CSP- Accept Proposed Solution On Case

- CSP- Provide Feedback on Survey

- CSP- Provide requested info on case

- CSP: Search On Homepage

- CSP: Create Product Case as Consumer from CSP Portal

- CSP: Register Your Product

**Comment by jacebenson** [comment]
I started pulling this and have been running it for the last 10 minutes.  Its very comprehensive.  Good job.  I need to restart it cause I failed to install the `com.sn_cs_sm` plugin.  But looking pretty good so far!

**Comment by SxMShaDoW** [comment]
In theory we could "speed" these up by converting some of the UI tests to API tests (backend tests with record query/insert mostly). It is mostly slow because it needs a client runner. 

The reason I created most of them as UI tests is my assumption is people want to know if the UI breaks more than the backend inserts break. Also the OOB ones were UI tests so I didn't want to stray away.

**Comment by jacebenson** [comment]
I just restarted it, disabled screenshots unless it fails, Seems much faster.

**Comment by jacebenson** [comment]
image

**Review by jacebenson — APPROVED** [review]
Looks good.  tested it out.  Tests are comprehensive, and passing.

**Comment by SxMShaDoW** [comment]
Woot! What is the best way to let people know what plugins they need installed in order to run these tells?

**Comment by jacebenson** [comment]
I almost think a step that fails due may be best.  it may be worth a discussion about how to show the status of this scoped app.  This isn't the first set of tests that needs specific plugins

Might be worth adding a SP portal/page to show the status of the things before running them with direct links to enable them.

**Comment by jacebenson** [comment]
Now im just retesting it from jacebenson/atf as that is always a concern.  no good way to ensure the scope isn't broken until retested.

Wow, that was a TON of tests.  Good job.  looks like everyhting installed and ran properly.

**Comment by SxMShaDoW** [comment]
Awesome :). You may want to close #23. 

I notice there is still #38 that could also be improved on. #186 will rename to follow the same standard you had

**Pull request merged**
